# Generated by Django 5.1 on 2024-08-30 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0007_remove_instanceresult_instance_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FPSMeasurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pretrained_backbone_name", models.CharField(max_length=100)),
                ("resolution", models.IntegerField()),
                ("fps", models.FloatField()),
                (
                    "gpu",
                    models.CharField(
                        choices=[
                            ("V100", "V100"),
                            ("A100", "A100"),
                            ("H100", "H100"),
                            ("T4", "T4"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "precision",
                    models.CharField(
                        blank=True,
                        choices=[("FP16", "FP16"), ("FP32", "FP32"), ("INT8", "INT8")],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "batch_size",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="batch size"
                    ),
                ),
                ("source", models.URLField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name="pretrainedbackbone",
            name="pretrain_method",
            field=models.CharField(
                choices=[
                    ("Supervised", "Supervised"),
                    ("FCMAE", "FCMAE"),
                    ("MAE", "MAE"),
                    ("CL", "CL"),
                ],
                max_length=100,
                verbose_name="pretraining method",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="name",
            field=models.CharField(
                choices=[
                    ("Classification", "Classification"),
                    ("Object Detection", "Object Detection"),
                    ("Instance Segmentation", "Instance Segmentation"),
                    ("Semantic Segmentation", "Semantic Segmentation"),
                    ("Panoptic Segmentation", "Panoptic Segmentation"),
                ],
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="backbone",
            name="fps_measurements",
            field=models.ManyToManyField(blank=True, to="stats.fpsmeasurement"),
        ),
    ]
