# Generated by Django 5.1 on 2024-08-31 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0010_alter_fpsmeasurement_precision"),
    ]

    operations = [
        migrations.AddField(
            model_name="classificationresult",
            name="resolution",
            field=models.IntegerField(default=224),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="instanceresult",
            name="fps_measurements",
            field=models.ManyToManyField(blank=True, to="stats.fpsmeasurement"),
        ),
        migrations.AlterField(
            model_name="fpsmeasurement",
            name="precision",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FP16", "FP16"),
                    ("FP32", "FP32"),
                    ("INT8", "INT8"),
                    ("AMP", "AMP"),
                    ("TF32", "TF32"),
                    ("BF16", "BF16"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
