# Generated by Django 5.1 on 2024-09-29 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0020_remove_classificationresult_pretrained_backbone_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backbone",
            name="family",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="stats.backbonefamily"
            ),
        ),
        migrations.AlterField(
            model_name="backbone",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="backbonefamily",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="classificationresult",
            name="dataset",
            field=models.ForeignKey(
                limit_choices_to={"tasks__name": "Classification"},
                on_delete=django.db.models.deletion.RESTRICT,
                to="stats.dataset",
            ),
        ),
        migrations.AlterField(
            model_name="classificationresult",
            name="fine_tune_dataset",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"tasks__name": "Classification"},
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="classification_fine_tune",
                to="stats.dataset",
            ),
        ),
        migrations.AlterField(
            model_name="classificationresult",
            name="intermediate_fine_tune_dataset",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"tasks__name": "Classification"},
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="intermediate_classification_fine_tune",
                to="stats.dataset",
            ),
        ),
        migrations.AlterField(
            model_name="classificationresult",
            name="pretrained_backbone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="stats.pretrainedbackbone",
            ),
        ),
        migrations.AlterField(
            model_name="classificationresult",
            name="top_1",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="instanceresult",
            name="dataset",
            field=models.ForeignKey(
                limit_choices_to={
                    "tasks__name__in": ["Object Detection", "Instance Segmentation"]
                },
                on_delete=django.db.models.deletion.RESTRICT,
                to="stats.dataset",
            ),
        ),
        migrations.AlterField(
            model_name="instanceresult",
            name="intermediate_train_dataset",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={
                    "tasks__name__in": ["Object Detection", "Instance Segmentation"]
                },
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="intermediate_instance_train",
                to="stats.dataset",
            ),
        ),
        migrations.AlterField(
            model_name="instanceresult",
            name="pretrained_backbone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="stats.pretrainedbackbone",
            ),
        ),
        migrations.AlterField(
            model_name="instanceresult",
            name="train_dataset",
            field=models.ForeignKey(
                limit_choices_to={
                    "tasks__name__in": ["Object Detection", "Instance Segmentation"]
                },
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="instance_train",
                to="stats.dataset",
            ),
        ),
        migrations.AlterField(
            model_name="pretrainedbackbone",
            name="backbone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="stats.backbone"
            ),
        ),
        migrations.AlterField(
            model_name="pretrainedbackbone",
            name="family",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="stats.backbonefamily"
            ),
        ),
        migrations.AlterField(
            model_name="pretrainedbackbone",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="pretrainedbackbone",
            name="pretrain_dataset",
            field=models.ForeignKey(
                limit_choices_to={"tasks__name": "Classification"},
                on_delete=django.db.models.deletion.RESTRICT,
                to="stats.dataset",
            ),
        ),
    ]
