# Generated by Django 5.1 on 2024-10-14 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0021_alter_backbone_family_alter_backbone_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backbonefamily",
            name="model_type",
            field=models.CharField(
                choices=[
                    ("Attention", "Attention"),
                    ("Convolution", "Convolution"),
                    ("LSTM", "LSTM"),
                    ("State Space Model", "State Space Model"),
                    ("Attn + Conv", "Attn + Conv"),
                    ("Conv + SSM", "Conv + SSM"),
                    ("Random", "Random"),
                    ("Identity", "Identity"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="instanceresult",
            name="train_epochs",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pretrainedbackbone",
            name="pretrain_epochs",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pretrainedbackbone",
            name="pretrain_resolution",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="SemanticSegmentationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("train_epochs", models.IntegerField()),
                ("train_resolution", models.IntegerField()),
                ("m_iou", models.FloatField()),
                ("pixel_accuracy", models.FloatField(blank=True, null=True)),
                ("mean_accuracy", models.FloatField(blank=True, null=True)),
                (
                    "multiscale",
                    models.BooleanField(
                        default=False, help_text="multiscale inference"
                    ),
                ),
                (
                    "flip_test",
                    models.BooleanField(
                        default=False, help_text="horizontal flip testing"
                    ),
                ),
                ("gflops", models.FloatField(blank=True, null=True)),
                ("paper", models.URLField(blank=True)),
                ("github", models.URLField(blank=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        limit_choices_to={"tasks__name": "Semantic Segmentation"},
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="semantic_seg_result",
                        to="stats.dataset",
                    ),
                ),
                (
                    "fps_measurements",
                    models.ManyToManyField(blank=True, to="stats.fpsmeasurement"),
                ),
                (
                    "head",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="stats.downstreamhead",
                    ),
                ),
                (
                    "pretrained_backbone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stats.pretrainedbackbone",
                    ),
                ),
                (
                    "train_dataset",
                    models.ForeignKey(
                        limit_choices_to={"tasks__name": "Semantic Segmentation"},
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="semantic_seg_train",
                        to="stats.dataset",
                    ),
                ),
            ],
        ),
    ]
