# Generated by Django 5.1 on 2024-10-15 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "stats",
            "0024_semanticsegmentationresult_intermediate_train_dataset_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="semanticsegmentationresult",
            old_name="train_resolution",
            new_name="crop_size",
        ),
        migrations.RemoveField(
            model_name="semanticsegmentationresult",
            name="intermediate_train_resolution",
        ),
    ]
