# Generated by Django 5.1 on 2025-04-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0026_alter_semanticsegmentationresult_dataset"),
    ]

    operations = [
        migrations.AddField(
            model_name="pretrainedbackbone",
            name="token_labelling",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="fpsmeasurement",
            name="gpu",
            field=models.CharField(
                choices=[
                    ("V100", "V100"),
                    ("A100", "A100"),
                    ("H100", "H100"),
                    ("T4", "T4"),
                    ("2080Ti", "2080Ti"),
                    ("3090", "3090"),
                    ("4090", "4090"),
                ],
                max_length=100,
            ),
        ),
    ]
