# Generated by Django 5.1 on 2025-04-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0027_pretrainedbackbone_token_labelling_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pretrainedbackbone",
            name="token_labelling",
        ),
        migrations.AlterField(
            model_name="backbonefamily",
            name="pretrain_method",
            field=models.CharField(
                choices=[
                    ("Supervised", "Supervised"),
                    ("Sup. + TL", "Sup. + TL"),
                    ("FCMAE", "FCMAE"),
                    ("MAE", "MAE"),
                    ("CL", "CL"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="pretrainedbackbone",
            name="pretrain_method",
            field=models.CharField(
                choices=[
                    ("Supervised", "Supervised"),
                    ("Sup. + TL", "Sup. + TL"),
                    ("FCMAE", "FCMAE"),
                    ("MAE", "MAE"),
                    ("CL", "CL"),
                ],
                max_length=100,
            ),
        ),
    ]
