# Generated by Django 5.1 on 2025-11-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0028_remove_pretrainedbackbone_token_labelling_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backbonefamily',
            name='pretrain_method',
            field=models.CharField(choices=[('Supervised', 'Supervised'), ('Sup. + TL', 'Sup. + TL'), ('FCMAE', 'FCMAE'), ('MAE', 'MAE'), ('CL', 'CL'), ('MAP', 'MAP')], max_length=100),
        ),
        migrations.AlterField(
            model_name='fpsmeasurement',
            name='gpu',
            field=models.CharField(choices=[('V100', 'V100'), ('A100', 'A100'), ('H100', 'H100'), ('T4', 'T4'), ('2080Ti', '2080Ti'), ('3080', '3080'), ('3090', '3090'), ('4090', '4090'), ('L40S', 'L40S')], max_length=100),
        ),
        migrations.AlterField(
            model_name='pretrainedbackbone',
            name='pretrain_method',
            field=models.CharField(choices=[('Supervised', 'Supervised'), ('Sup. + TL', 'Sup. + TL'), ('FCMAE', 'FCMAE'), ('MAE', 'MAE'), ('CL', 'CL'), ('MAP', 'MAP')], max_length=100),
        ),
    ]
