# Generated by Django 5.1 on 2026-09-25 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0001_initial"),
        ("stats", "0029_alter_backbonefamily_pretrain_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="backbone",
            name="source_record",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="ingestion.extractedrecord",
            ),
        ),
        migrations.AddField(
            model_name="backbonefamily",
            name="source_record",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="ingestion.extractedrecord",
            ),
        ),
        migrations.AddField(
            model_name="classificationresult",
            name="source_record",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="ingestion.extractedrecord",
            ),
        ),
        migrations.AddField(
            model_name="dataset",
            name="source_record",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="ingestion.extractedrecord",
            ),
        ),
        migrations.AddField(
            model_name="downstreamhead",
            name="source_record",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="ingestion.extractedrecord",
            ),
        ),
        migrations.AddField(
            model_name="fpsmeasurement",
            name="source_record",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="ingestion.extractedrecord",
            ),
        ),
        migrations.AddField(
            model_name="instanceresult",
            name="source_record",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="ingestion.extractedrecord",
            ),
        ),
        migrations.AddField(
            model_name="pretrainedbackbone",
            name="source_record",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="ingestion.extractedrecord",
            ),
        ),
        migrations.AddField(
            model_name="semanticsegmentationresult",
            name="source_record",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="ingestion.extractedrecord",
            ),
        ),
        migrations.AlterField(
            model_name="backbone",
            name="m_parameters",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="backbonefamily",
            name="hierarchical",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="backbonefamily",
            name="model_type",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="backbonefamily",
            name="pretrain_method",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="classificationresult",
            name="fine_tune_epochs",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="classificationresult",
            name="intermediate_fine_tune_epochs",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="instanceresult",
            name="intermediate_train_epochs",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="instanceresult",
            name="train_dataset",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={
                    "tasks__name__in": ["Object Detection", "Instance Segmentation"]
                },
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="instance_train",
                to="stats.dataset",
            ),
        ),
        migrations.AlterField(
            model_name="instanceresult",
            name="train_epochs",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pretrainedbackbone",
            name="pretrain_dataset",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"tasks__name": "Classification"},
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="stats.dataset",
            ),
        ),
        migrations.AlterField(
            model_name="pretrainedbackbone",
            name="pretrain_epochs",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pretrainedbackbone",
            name="pretrain_method",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="pretrainedbackbone",
            name="pretrain_resolution",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="semanticsegmentationresult",
            name="crop_size",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="semanticsegmentationresult",
            name="flip_test",
            field=models.BooleanField(
                blank=True, default=None, help_text="horizontal flip testing", null=True
            ),
        ),
        migrations.AlterField(
            model_name="semanticsegmentationresult",
            name="intermediate_train_epochs",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="semanticsegmentationresult",
            name="train_dataset",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"tasks__name": "Semantic Segmentation"},
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="semantic_seg_train",
                to="stats.dataset",
            ),
        ),
        migrations.AlterField(
            model_name="semanticsegmentationresult",
            name="train_epochs",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
