# Generated by Django 5.1 on 2026-09-25 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0030_backbone_source_record_backbonefamily_source_record_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backbone',
            name='m_parameters',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='backbonefamily',
            name='hierarchical',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='backbonefamily',
            name='pretrain_method',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='instanceresult',
            name='train_dataset',
            field=models.ForeignKey(limit_choices_to={'tasks__name__in': ['Object Detection', 'Instance Segmentation']}, on_delete=django.db.models.deletion.RESTRICT, related_name='instance_train', to='stats.dataset'),
        ),
        migrations.AlterField(
            model_name='instanceresult',
            name='train_epochs',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pretrainedbackbone',
            name='pretrain_dataset',
            field=models.ForeignKey(limit_choices_to={'tasks__name': 'Classification'}, on_delete=django.db.models.deletion.RESTRICT, to='stats.dataset'),
        ),
        migrations.AlterField(
            model_name='pretrainedbackbone',
            name='pretrain_epochs',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pretrainedbackbone',
            name='pretrain_method',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pretrainedbackbone',
            name='pretrain_resolution',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='semanticsegmentationresult',
            name='crop_size',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='semanticsegmentationresult',
            name='flip_test',
            field=models.BooleanField(default=False, help_text='horizontal flip testing'),
        ),
        migrations.AlterField(
            model_name='semanticsegmentationresult',
            name='train_dataset',
            field=models.ForeignKey(limit_choices_to={'tasks__name': 'Semantic Segmentation'}, on_delete=django.db.models.deletion.RESTRICT, related_name='semantic_seg_train', to='stats.dataset'),
        ),
        migrations.AlterField(
            model_name='semanticsegmentationresult',
            name='train_epochs',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('model_type', 'Model Type'), ('pretrain_method', 'Pretrain Method')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('approved_by', models.CharField(max_length=150)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'categories',
                'constraints': [models.UniqueConstraint(fields=('scope', 'name'), name='unique_category')],
            },
        ),
    ]
