# Generated by Django 5.1 on 2026-10-02 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0031_restore_required_fields_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="backbonefamily",
            name="spiking",
            field=models.BooleanField(default=False),
        ),
    ]
