# Generated by Django 5.1 on 2024-08-19 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("view", "0006_classificationresult_pretrained_backbone_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instanceresult",
            name="instance_type",
        ),
        migrations.AddField(
            model_name="instanceresult",
            name="instance_type",
            field=models.ForeignKey(
                default=4, on_delete=django.db.models.deletion.CASCADE, to="view.task"
            ),
            preserve_default=False,
        ),
    ]
