# Generated by Django 5.1 on 2024-08-30 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("view", "0008_fpsmeasurement_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fpsmeasurement",
            old_name="pretrained_backbone_name",
            new_name="backbone_name",
        ),
    ]
