# Generated by Django 5.1 on 2024-08-30 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("view", "0009_rename_pretrained_backbone_name_fpsmeasurement_backbone_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fpsmeasurement",
            name="precision",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FP16", "FP16"),
                    ("FP32", "FP32"),
                    ("INT8", "INT8"),
                    ("AMP", "AMP"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
