# Generated by Django 5.1 on 2026-09-25 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IngestionRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("rejected", "Rejected"),
                            ("review", "Needs review"),
                            ("ready", "Ready"),
                            ("imported", "Imported"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="running",
                        max_length=20,
                    ),
                ),
                ("provider", models.CharField(max_length=20)),
                ("model", models.CharField(max_length=100)),
                ("prompt_version", models.CharField(max_length=50)),
                ("code_version", models.CharField(max_length=100)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("decision", models.JSONField(default=dict)),
                (
                    "calls",
                    models.JSONField(
                        default=list,
                        help_text="Requests, responses and usage; never API keys",
                    ),
                ),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                (
                    "estimated_cost",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=12, null=True
                    ),
                ),
                ("error", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="ExtractedRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=150)),
                ("kind", models.CharField(max_length=40)),
                ("data", models.JSONField(default=dict)),
                ("evidence", models.JSONField(default=list)),
                ("issues", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("imported", "Imported"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_by", models.CharField(blank=True, max_length=150)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_note", models.TextField(blank=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="records",
                        to="ingestion.ingestionrun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaperVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("arxiv_id", models.CharField(max_length=50)),
                (
                    "revision",
                    models.CharField(
                        help_text="Discovery source's updated timestamp", max_length=100
                    ),
                ),
                ("version", models.PositiveIntegerField(blank=True, null=True)),
                ("title", models.TextField()),
                ("abstract", models.TextField(blank=True)),
                ("metadata", models.JSONField(default=dict)),
                ("discovered_at", models.DateTimeField(auto_now_add=True)),
                ("existing_in_database", models.BooleanField(default=False)),
                ("pdf", models.FileField(blank=True, upload_to="papers/%Y/%m/")),
                ("sha256", models.CharField(blank=True, max_length=64)),
                (
                    "pages",
                    models.JSONField(
                        default=list, help_text="Extracted text, in PDF page order"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("arxiv_id", "revision"), name="unique_paper_revision"
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="ingestionrun",
            name="paper",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="runs",
                to="ingestion.paperversion",
            ),
        ),
        migrations.CreateModel(
            name="ImportChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=100)),
                ("object_id", models.PositiveBigIntegerField()),
                ("before", models.JSONField(blank=True, null=True)),
                ("after", models.JSONField()),
                ("actor", models.CharField(max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="changes",
                        to="ingestion.extractedrecord",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["model", "object_id"], name="import_target_idx"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="extractedrecord",
            constraint=models.UniqueConstraint(
                fields=("run", "key"), name="unique_extraction_key"
            ),
        ),
    ]
