# Generated by Django 5.1 on 2026-09-25 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedrecord',
            name='uncertain',
            field=models.JSONField(default=list, help_text='Fields the model could not establish, with reasons'),
        ),
        migrations.AddField(
            model_name='importchange',
            name='origin',
            field=models.CharField(blank=True, help_text='YAML file for a manual import', max_length=300),
        ),
        migrations.AddField(
            model_name='importchange',
            name='run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='changes', to='ingestion.ingestionrun'),
        ),
        migrations.AlterField(
            model_name='importchange',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='changes', to='ingestion.extractedrecord'),
        ),
    ]
