# Generated by Django 5.1 on 2026-09-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_uncertain_fields_manual_import_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedrecord',
            name='inferred',
            field=models.JSONField(default=list, help_text='Reference/classification fields implied, not quoted, with their source'),
        ),
        migrations.AddField(
            model_name='extractedrecord',
            name='note',
            field=models.TextField(blank=True, help_text="The model's judgment calls for this record"),
        ),
        migrations.AlterField(
            model_name='ingestionrun',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('shortlisted', 'Shortlisted: abstract passed, awaiting full read'), ('rejected', 'Rejected'), ('review', 'Needs review'), ('ready', 'Ready'), ('imported', 'Imported'), ('failed', 'Failed')], db_index=True, default='running', max_length=20),
        ),
    ]
