# Generated by Django 5.1 on 2026-09-26 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0003_shortlisted_status_record_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('fetched_from', models.URLField(help_text='The URL actually downloaded (e.g. the raw README)', max_length=500)),
                ('fetched_at', models.DateTimeField()),
                ('sha256', models.CharField(max_length=64)),
                ('text', models.TextField()),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sources', to='ingestion.ingestionrun')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('run', 'url'), name='unique_run_source')],
            },
        ),
    ]
