# Generated by Django 5.1 on 2026-09-26 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0004_web_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedrecord',
            name='overrides',
            field=models.JSONField(default=list, help_text='Values corrected by a reviewer: field, old and new value, who, why'),
        ),
    ]
