# Generated by Django 5.1 on 2026-09-26 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0005_record_overrides'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestionrun',
            name='feedback',
            field=models.TextField(blank=True, help_text="The reviewer's note that asked for this retry"),
        ),
        migrations.AddField(
            model_name='ingestionrun',
            name='retry_of',
            field=models.ForeignKey(blank=True, help_text='The rejected run this one retries', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retries', to='ingestion.ingestionrun'),
        ),
    ]
