name: A2Mamba
model_type: Attn + Conv
hierarchical: true
pretrain_method: Supervised
pub_date: '2025-07-22'
paper: https://arxiv.org/abs/2507.16624
github: https://github.com/LMMMEng/A2Mamba
backbones:
- name: A2Mamba-N
  m_parameters: 4.0
  fps_measurements:
  - resolution: 224
    gpu: L40S
    precision: FP32
    fps: 2486
    batch_size: 128
  pretrained_backbones:
  - name: A2Mamba-N-IN1k
    pretrain_dataset: ImageNet-1k
    pretrain_method: Supervised
    pretrain_resolution: 224
    pretrain_epochs: 300
    classification_results:
    - dataset: ImageNet-1k
      resolution: 224
      top_1: 78.7
      top_5: null
      gflops: 0.8
- name: A2Mamba-T
  m_parameters: 15.0
  fps_measurements:
  - resolution: 224
    gpu: L40S
    precision: FP32
    fps: 1287
    batch_size: 128
  pretrained_backbones:
  - name: A2Mamba-T-IN1k
    pretrain_dataset: ImageNet-1k
    pretrain_method: Supervised
    pretrain_resolution: 224
    pretrain_epochs: 300
    classification_results:
    - dataset: ImageNet-1k
      resolution: 224
      top_1: 83.0
      top_5: null
      gflops: 2.7
- name: A2Mamba-S
  m_parameters: 31.0
  fps_measurements:
  - resolution: 224
    gpu: L40S
    precision: FP32
    fps: 762
    batch_size: 128
  pretrained_backbones:
  - name: A2Mamba-S-IN1k
    pretrain_dataset: ImageNet-1k
    pretrain_method: Supervised
    pretrain_resolution: 224
    pretrain_epochs: 300
    classification_results:
    - dataset: ImageNet-1k
      resolution: 224
      top_1: 84.7
      top_5: null
      gflops: 5.4
    instance_results:
    - head: Mask R-CNN
      dataset: COCO (val)
      instance_type: Object Detection
      train_dataset: COCO (train)
      train_epochs: 36
      mAP: 51.5
      AP50: null
      AP75: null
      mAPs: null
      mAPm: null
      mAPl: null
      gflops: 283.0
    - head: Mask R-CNN
      dataset: COCO (val)
      instance_type: Instance Segmentation
      train_dataset: COCO (train)
      train_epochs: 36
      mAP: 45.3
      AP50: null
      AP75: null
      mAPs: null
      mAPm: null
      mAPl: null
      gflops: 283.0
    - head: Cascade Mask R-CNN
      dataset: COCO (val)
      instance_type: Object Detection
      train_dataset: COCO (train)
      train_epochs: 36
      mAP: 54.0
      AP50: null
      AP75: null
      mAPs: null
      mAPm: null
      mAPl: null
      gflops: 762.0
    - head: Cascade Mask R-CNN
      dataset: COCO (val)
      instance_type: Instance Segmentation
      train_dataset: COCO (train)
      train_epochs: 36
      mAP: 46.6
      AP50: null
      AP75: null
      mAPs: null
      mAPm: null
      mAPl: null
      gflops: 762.0
    semantic_seg_results:
    - head: UPerNet
      dataset: ADE20K (val)
      train_dataset: ADE20K (train)
      train_epochs: 128
      crop_size: 512
      ms_m_iou: 52.0
      ms_pixel_accuracy: null
      ms_mean_accuracy: null
      ss_m_iou: 51.6
      ss_pixel_accuracy: null
      ss_mean_accuracy: null
      flip_test: true
      gflops: 959.0
- name: A2Mamba-B
  m_parameters: 51.0
  fps_measurements:
  - resolution: 224
    gpu: L40S
    precision: FP32
    fps: 320
    batch_size: 128
  pretrained_backbones:
  - name: A2Mamba-B-IN1k
    pretrain_dataset: ImageNet-1k
    pretrain_method: Supervised
    pretrain_resolution: 224
    pretrain_epochs: 300
    classification_results:
    - dataset: ImageNet-1k
      resolution: 224
      top_1: 85.7
      top_5: null
      gflops: 10.7
    - dataset: ImageNet-1k
      resolution: 384
      fine_tune_dataset: ImageNet-1k
      fine_tune_epochs: 30
      fine_tune_resolution: 384
      top_1: 86.4
      top_5: null
      gflops: 34.0
    instance_results:
    - head: Mask R-CNN
      dataset: COCO (val)
      instance_type: Object Detection
      train_dataset: COCO (train)
      train_epochs: 36
      mAP: 52.7
      AP50: null
      AP75: null
      mAPs: null
      mAPm: null
      mAPl: null
      gflops: 410.0
    - head: Mask R-CNN
      dataset: COCO (val)
      instance_type: Instance Segmentation
      train_dataset: COCO (train)
      train_epochs: 36
      mAP: 46.8
      AP50: null
      AP75: null
      mAPs: null
      mAPm: null
      mAPl: null
      gflops: 410.0
    - head: Cascade Mask R-CNN
      dataset: COCO (val)
      instance_type: Object Detection
      train_dataset: COCO (train)
      train_epochs: 36
      mAP: 55.4
      AP50: null
      AP75: null
      mAPs: null
      mAPm: null
      mAPl: null
      gflops: 889.0
    - head: Cascade Mask R-CNN
      dataset: COCO (val)
      instance_type: Instance Segmentation
      train_dataset: COCO (train)
      train_epochs: 36
      mAP: 47.6
      AP50: null
      AP75: null
      mAPs: null
      mAPm: null
      mAPl: null
      gflops: 889.0
    semantic_seg_results:
    - head: UPerNet
      dataset: ADE20K (val)
      train_dataset: ADE20K (train)
      train_epochs: 128
      crop_size: 512
      ms_m_iou: 53.9
      ms_pixel_accuracy: null
      ms_mean_accuracy: null
      ss_m_iou: 53.3
      ss_pixel_accuracy: null
      ss_mean_accuracy: null
      flip_test: true
      gflops: 1090.0
- name: A2Mamba-L
  m_parameters: 95.0
  fps_measurements:
  - resolution: 224
    gpu: L40S
    precision: FP32
    fps: 258
    batch_size: 128
  pretrained_backbones:
  - name: A2Mamba-L-IN1k
    pretrain_dataset: ImageNet-1k
    pretrain_method: Supervised
    pretrain_resolution: 224
    pretrain_epochs: 300
    classification_results:
    - dataset: ImageNet-1k
      resolution: 224
      top_1: 86.1
      top_5: null
      gflops: 17.4
    - dataset: ImageNet-1k
      resolution: 384
      fine_tune_dataset: ImageNet-1k
      fine_tune_epochs: 30
      fine_tune_resolution: 384
      top_1: 86.7
      top_5: null
      gflops: 54.0
    instance_results:
    - head: Mask R-CNN
      dataset: COCO (val)
      instance_type: Object Detection
      train_dataset: COCO (train)
      train_epochs: 36
      mAP: 53.0
      AP50: null
      AP75: null
      mAPs: null
      mAPm: null
      mAPl: null
      gflops: 552.0
    - head: Mask R-CNN
      dataset: COCO (val)
      instance_type: Instance Segmentation
      train_dataset: COCO (train)
      train_epochs: 36
      mAP: 46.8
      AP50: null
      AP75: null
      mAPs: null
      mAPm: null
      mAPl: null
      gflops: 552.0
    - head: Cascade Mask R-CNN
      dataset: COCO (val)
      instance_type: Object Detection
      train_dataset: COCO (train)
      train_epochs: 36
      mAP: 55.6
      AP50: null
      AP75: null
      mAPs: null
      mAPm: null
      mAPl: null
      gflops: 1027.0
    - head: Cascade Mask R-CNN
      dataset: COCO (val)
      instance_type: Instance Segmentation
      train_dataset: COCO (train)
      train_epochs: 36
      mAP: 48.1
      AP50: null
      AP75: null
      mAPs: null
      mAPm: null
      mAPl: null
      gflops: 1027.0
    semantic_seg_results:
    - head: UPerNet
      dataset: ADE20K (val)
      train_dataset: ADE20K (train)
      train_epochs: 128
      crop_size: 512
      ms_m_iou: 54.1
      ms_pixel_accuracy: null
      ms_mean_accuracy: null
      ss_m_iou: 53.7
      ss_pixel_accuracy: null
      ss_mean_accuracy: null
      flip_test: true
      gflops: 1237.0
