name: CoCA ViT
model_type: Attn + Conv
hierarchical: true
pretrain_method: Supervised
pub_date: '2025-08-07'
paper: https://arxiv.org/abs/2508.05307v1
github: https://github.com
backbones:
- name: CoCA ViT-11M
  m_parameters: 11.4
  fps_measurements:
  - resolution: 224
    gpu: 3080
    precision: AMP
    fps: 1387
    batch_size: 32
  pretrained_backbones:
  - name: CoCA ViT-11M-IN1k
    pretrain_dataset: ImageNet-1k
    pretrain_method: Supervised
    pretrain_resolution: 224
    pretrain_epochs: 300
    classification_results:
    - dataset: ImageNet-1k
      resolution: 224
      top_1: 82.7
      top_5: null
      gflops: 2.2
    - dataset: ImageNet-ReaL
      resolution: 224
      top_1: 87.8
      top_5: null
      gflops: 2.2
    - dataset: ImageNet-V2
      resolution: 224
      top_1: 72.9
      top_5: null
      gflops: 2.2
    - dataset: ImageNet-A
      resolution: 224
      top_1: 34.1
      top_5: null
      gflops: 2.2
    - dataset: ImageNet-R
      resolution: 224
      top_1: 47.8
      top_5: null
      gflops: 2.2
    - dataset: ImageNet-Sketch
      resolution: 224
      top_1: 35.5
      top_5: null
      gflops: 2.2
    instance_results: []
    semantic_seg_results: []
- name: CoCA ViT-21M
  m_parameters: 20.6
  fps_measurements:
  - resolution: 224
    gpu: 3080
    precision: AMP
    fps: 902
    batch_size: 32
  pretrained_backbones:
  - name: CoCA ViT-21M-IN1k
    pretrain_dataset: ImageNet-1k
    pretrain_method: Supervised
    pretrain_resolution: 224
    pretrain_epochs: 300
    classification_results:
    - dataset: ImageNet-1k
      resolution: 224
      top_1: 83.6
      top_5: null
      gflops: 4.1
    - dataset: ImageNet-ReaL
      resolution: 224
      top_1: 88.3
      top_5: null
      gflops: 4.1
    - dataset: ImageNet-V2
      resolution: 224
      top_1: 73.7
      top_5: null
      gflops: 4.1
    - dataset: ImageNet-A
      resolution: 224
      top_1: 38.9
      top_5: null
      gflops: 4.1
    - dataset: ImageNet-R
      resolution: 224
      top_1: 50.1
      top_5: null
      gflops: 4.1
    - dataset: ImageNet-Sketch
      resolution: 224
      top_1: 39.6
      top_5: null
      gflops: 4.1
    instance_results:
    - head: Cascade Mask R-CNN
      dataset: COCO (val)
      instance_type: Object Detection
      train_dataset: COCO (train)
      train_epochs: 36
      mAP: 51.8
      AP50: 70.5
      AP75: 56.1
      mAPs: null
      mAPm: null
      mAPl: null
      gflops: null
    - head: Cascade Mask R-CNN
      dataset: COCO (val)
      instance_type: Instance Segmentation
      train_dataset: COCO (train)
      train_epochs: 36
      mAP: 44.9
      AP50: 67.8
      AP75: 48.2
      mAPs: null
      mAPm: null
      mAPl: null
      gflops: null
    semantic_seg_results:
    - head: UPerNet
      dataset: ADE20K (val)
      train_dataset: ADE20K (train)
      train_epochs: 128
      crop_size: 512
      ms_m_iou: 50.8
      ms_pixel_accuracy: null
      ms_mean_accuracy: null
      ss_m_iou: null
      ss_pixel_accuracy: null
      ss_mean_accuracy: null
      flip_test: true
      gflops: null
- name: CoCA ViT-28M
  m_parameters: 27.8
  fps_measurements:
  - resolution: 224
    gpu: 3080
    precision: AMP
    fps: 791
    batch_size: 32
  pretrained_backbones:
  - name: CoCA ViT-28M-IN1k
    pretrain_dataset: ImageNet-1k
    pretrain_method: Supervised
    pretrain_resolution: 224
    pretrain_epochs: 300
    classification_results:
    - dataset: ImageNet-1k
      resolution: 224
      top_1: 84.0
      top_5: null
      gflops: 4.9
    - dataset: ImageNet-ReaL
      resolution: 224
      top_1: 88.4
      top_5: null
      gflops: 4.9
    - dataset: ImageNet-V2
      resolution: 224
      top_1: 74.0
      top_5: null
      gflops: 4.9
    - dataset: ImageNet-A
      resolution: 224
      top_1: 39.8
      top_5: null
      gflops: 4.9
    - dataset: ImageNet-R
      resolution: 224
      top_1: 51.1
      top_5: null
      gflops: 4.9
    - dataset: ImageNet-Sketch
      resolution: 224
      top_1: 40.2
      top_5: null
      gflops: 4.9
    instance_results:
    - head: Cascade Mask R-CNN
      dataset: COCO (val)
      instance_type: Object Detection
      train_dataset: COCO (train)
      train_epochs: 36
      mAP: 52.2
      AP50: 71.0
      AP75: 56.8
      mAPs: null
      mAPm: null
      mAPl: null
      gflops: null
    - head: Cascade Mask R-CNN
      dataset: COCO (val)
      instance_type: Instance Segmentation
      train_dataset: COCO (train)
      train_epochs: 36
      mAP: 45.2
      AP50: 68.9
      AP75: 48.8
      mAPs: null
      mAPm: null
      mAPl: null
      gflops: null
    semantic_seg_results:
    - head: UPerNet
      dataset: ADE20K (val)
      train_dataset: ADE20K (train)
      train_epochs: 128
      crop_size: 512
      ms_m_iou: 51.3
      ms_pixel_accuracy: null
      ms_mean_accuracy: null
      ss_m_iou: null
      ss_pixel_accuracy: null
      ss_mean_accuracy: null
      flip_test: true
      gflops: null
