name: FractalMamba++
model_type: State Space Model
hierarchical: true
pretrain_method: Supervised
pub_date: '2025-08-13'
paper: https://arxiv.org/abs/2505.14062
github: https://github.com
backbones:
- name: FractalMamba++ (T)
  m_parameters: 30.0
  fps_measurements:
  - resolution: 224
    gpu: H100
    precision: AMP
    fps: 302
    batch_size: 32
  pretrained_backbones:
  - name: FractalMamba++ (T)-IN1k
    pretrain_dataset: ImageNet-1k
    pretrain_method: Supervised
    pretrain_resolution: 224
    pretrain_epochs: 300
    classification_results:
    - dataset: ImageNet-1k
      resolution: 224
      top_1: 83.0
      top_5: null
      gflops: 4.8
    - dataset: ImageNet-1k
      resolution: 256
      top_1: 83.5
      top_5: null
      gflops: null
    - dataset: ImageNet-1k
      resolution: 384
      top_1: 84.1
      top_5: null
      gflops: null
    - dataset: ImageNet-1k
      resolution: 512
      top_1: 83.9
      top_5: null
      gflops: null
    - dataset: ImageNet-1k
      resolution: 640
      top_1: 83.0
      top_5: null
      gflops: null
    - dataset: ImageNet-1k
      resolution: 768
      top_1: 81.9
      top_5: null
      gflops: null
    - dataset: ImageNet-1k
      resolution: 1024
      top_1: 78.8
      top_5: null
      gflops: null
    - dataset: ImageNet-1k
      resolution: 1280
      top_1: 74.3
      top_5: null
      gflops: null
    - dataset: ImageNet-1k
      resolution: 1408
      top_1: 71.3
      top_5: null
      gflops: null
    - dataset: ImageNet-1k
      resolution: 1536
      top_1: 67.5
      top_5: null
      gflops: null
    instance_results:
    - head: Mask R-CNN
      dataset: COCO (val)
      instance_type: Object Detection
      train_dataset: COCO (train)
      train_epochs: 12
      mAP: 47.8
      AP50: 69.8
      AP75: 52.5
      mAPs: null
      mAPm: null
      mAPl: null
      gflops: 260.0
    - head: Mask R-CNN
      dataset: COCO (val)
      instance_type: Instance Segmentation
      train_dataset: COCO (train)
      train_epochs: 12
      mAP: 43.2
      AP50: 66.8
      AP75: 46.6
      mAPs: null
      mAPm: null
      mAPl: null
      gflops: 260.0
    - head: Mask R-CNN
      dataset: COCO (val)
      instance_type: Object Detection
      train_dataset: COCO (train)
      train_epochs: 36
      mAP: 49.5
      AP50: 71.0
      AP75: 54.6
      mAPs: null
      mAPm: null
      mAPl: null
      gflops: 260.0
    - head: Mask R-CNN
      dataset: COCO (val)
      instance_type: Instance Segmentation
      train_dataset: COCO (train)
      train_epochs: 36
      mAP: 44.1
      AP50: 67.9
      AP75: 47.5
      mAPs: null
      mAPm: null
      mAPl: null
      gflops: 260.0
    semantic_seg_results:
    - head: UPerNet
      dataset: ADE20K (val)
      train_dataset: ADE20K (train)
      train_epochs: 640
      crop_size: 512
      ms_m_iou: 49.7
      ms_pixel_accuracy: null
      ms_mean_accuracy: null
      ss_m_iou: 48.8
      ss_pixel_accuracy: null
      ss_mean_accuracy: null
      flip_test: false
      gflops: 957.0
- name: FractalMamba++ (M)
  m_parameters: 11.0
  fps_measurements:
  - resolution: 224
    gpu: H100
    precision: AMP
    fps: 511
    batch_size: 32
  pretrained_backbones:
  - name: FractalMamba++ (M)-IN1k
    pretrain_dataset: ImageNet-1k
    pretrain_method: Supervised
    pretrain_resolution: 224
    pretrain_epochs: 300
    classification_results:
    - dataset: ImageNet-1k
      resolution: 224
      top_1: 79.5
      top_5: null
      gflops: 1.6
    - dataset: ImageNet-1k
      resolution: 256
      top_1: 80.6
      top_5: null
      gflops: null
    - dataset: ImageNet-1k
      resolution: 384
      top_1: 82.0
      top_5: null
      gflops: null
    - dataset: ImageNet-1k
      resolution: 512
      top_1: 81.3
      top_5: null
      gflops: null
    - dataset: ImageNet-1k
      resolution: 640
      top_1: 80.1
      top_5: null
      gflops: null
    - dataset: ImageNet-1k
      resolution: 768
      top_1: 78.3
      top_5: null
      gflops: null
    - dataset: ImageNet-1k
      resolution: 1024
      top_1: 73.3
      top_5: null
      gflops: null
    - dataset: ImageNet-1k
      resolution: 1280
      top_1: 66.3
      top_5: null
      gflops: null
    - dataset: ImageNet-1k
      resolution: 1408
      top_1: 61.7
      top_5: null
      gflops: null
    - dataset: ImageNet-1k
      resolution: 1536
      top_1: 56.1
      top_5: null
      gflops: null
    instance_results:
    - head: Mask R-CNN
      dataset: COCO (val)
      instance_type: Object Detection
      train_dataset: COCO (train)
      train_epochs: 12
      mAP: 44.1
      AP50: 66.2
      AP75: 48.0
      mAPs: null
      mAPm: null
      mAPl: null
      gflops: 199.0
    - head: Mask R-CNN
      dataset: COCO (val)
      instance_type: Instance Segmentation
      train_dataset: COCO (train)
      train_epochs: 12
      mAP: 40.3
      AP50: 63.2
      AP75: 43.4
      mAPs: null
      mAPm: null
      mAPl: null
      gflops: 199.0
    - head: Mask R-CNN
      dataset: COCO (val)
      instance_type: Object Detection
      train_dataset: COCO (train)
      train_epochs: 36
      mAP: 46.8
      AP50: 68.5
      AP75: 51.3
      mAPs: null
      mAPm: null
      mAPl: null
      gflops: 199.0
    - head: Mask R-CNN
      dataset: COCO (val)
      instance_type: Instance Segmentation
      train_dataset: COCO (train)
      train_epochs: 36
      mAP: 42.2
      AP50: 65.4
      AP75: 45.3
      mAPs: null
      mAPm: null
      mAPl: null
      gflops: 199.0
    semantic_seg_results:
    - head: UPerNet
      dataset: ADE20K (val)
      train_dataset: ADE20K (train)
      train_epochs: 640
      crop_size: 512
      ms_m_iou: 46.2
      ms_pixel_accuracy: null
      ms_mean_accuracy: null
      ss_m_iou: 45.8
      ss_pixel_accuracy: null
      ss_mean_accuracy: null
      flip_test: false
      gflops: 889.0
- name: FractalMamba++ (N)
  m_parameters: 7.0
  fps_measurements:
  - resolution: 224
    gpu: H100
    precision: AMP
    fps: 613
    batch_size: 32
  pretrained_backbones:
  - name: FractalMamba++ (N)-IN1k
    pretrain_dataset: ImageNet-1k
    pretrain_method: Supervised
    pretrain_resolution: 224
    pretrain_epochs: 300
    classification_results:
    - dataset: ImageNet-1k
      resolution: 224
      top_1: 77.3
      top_5: null
      gflops: 1.0
    - dataset: ImageNet-1k
      resolution: 256
      top_1: 78.4
      top_5: null
      gflops: null
    - dataset: ImageNet-1k
      resolution: 384
      top_1: 79.5
      top_5: null
      gflops: null
    - dataset: ImageNet-1k
      resolution: 512
      top_1: 78.4
      top_5: null
      gflops: null
    - dataset: ImageNet-1k
      resolution: 640
      top_1: 76.4
      top_5: null
      gflops: null
    - dataset: ImageNet-1k
      resolution: 768
      top_1: 73.7
      top_5: null
      gflops: null
    - dataset: ImageNet-1k
      resolution: 1024
      top_1: 66.5
      top_5: null
      gflops: null
    - dataset: ImageNet-1k
      resolution: 1280
      top_1: 55.2
      top_5: null
      gflops: null
    - dataset: ImageNet-1k
      resolution: 1408
      top_1: 48.1
      top_5: null
      gflops: null
    - dataset: ImageNet-1k
      resolution: 1536
      top_1: 42.5
      top_5: null
      gflops: null
    semantic_seg_results:
    - head: UPerNet
      dataset: ADE20K (val)
      train_dataset: ADE20K (train)
      train_epochs: 640
      crop_size: 512
      ms_m_iou: 45.0
      ms_pixel_accuracy: null
      ms_mean_accuracy: null
      ss_m_iou: 44.5
      ss_pixel_accuracy: null
      ss_mean_accuracy: null
      flip_test: false
      gflops: 860.0
