name: Iwin Transformer
model_type: Attn + Conv
hierarchical: true
pretrain_method: Supervised
pub_date: '2025-07-24'
paper: https://arxiv.org/abs/2507.18405v1
github: https://github.com/cominder/Iwin-Transformer
backbones:
- name: Iwin-T
  m_parameters: 30.2
  fps_measurements:
  - resolution: 224
    gpu: V100
    precision: FP32
    fps: 729
    batch_size: 256
  pretrained_backbones:
  - name: Iwin-T-IN1k
    pretrain_dataset: ImageNet-1k
    pretrain_method: Supervised
    pretrain_resolution: 224
    pretrain_epochs: 300
    classification_results:
    - dataset: ImageNet-1k
      resolution: 224
      top_1: 82.0
      top_5: null
      gflops: 4.7
    instance_results:
    - head: Mask R-CNN
      dataset: COCO (val)
      instance_type: Object Detection
      train_dataset: COCO (train)
      train_epochs: 12
      mAP: 42.2
      AP50: 65.3
      AP75: 45.8
      mAPs: null
      mAPm: null
      mAPl: null
      gflops: 268.0
    - head: Mask R-CNN
      dataset: COCO (val)
      instance_type: Instance Segmentation
      train_dataset: COCO (train)
      train_epochs: 12
      mAP: 38.9
      AP50: 62.1
      AP75: 41.6
      mAPs: null
      mAPm: null
      mAPl: null
      gflops: 268.0
    - head: Mask R-CNN
      dataset: COCO (val)
      instance_type: Object Detection
      train_dataset: COCO (train)
      train_epochs: 36
      mAP: 44.7
      AP50: 67.2
      AP75: 48.8
      mAPs: null
      mAPm: null
      mAPl: null
      gflops: 268.0
    - head: Mask R-CNN
      dataset: COCO (val)
      instance_type: Instance Segmentation
      train_dataset: COCO (train)
      train_epochs: 36
      mAP: 40.9
      AP50: 64.1
      AP75: 43.6
      mAPs: null
      mAPm: null
      mAPl: null
      gflops: 268.0
    - head: Cascade Mask R-CNN
      dataset: COCO (val)
      instance_type: Object Detection
      train_dataset: COCO (train)
      train_epochs: 12
      mAP: 47.2
      AP50: 66.1
      AP75: 51.3
      mAPs: null
      mAPm: null
      mAPl: null
      gflops: 747.0
    - head: Cascade Mask R-CNN
      dataset: COCO (val)
      instance_type: Instance Segmentation
      train_dataset: COCO (train)
      train_epochs: 12
      mAP: 40.9
      AP50: 63.5
      AP75: 44.1
      mAPs: null
      mAPm: null
      mAPl: null
      gflops: 747.0
    - head: Cascade Mask R-CNN
      dataset: COCO (val)
      instance_type: Object Detection
      train_dataset: COCO (train)
      train_epochs: 36
      mAP: 49.4
      AP50: 68.4
      AP75: 53.5
      mAPs: null
      mAPm: null
      mAPl: null
      gflops: 747.0
    - head: Cascade Mask R-CNN
      dataset: COCO (val)
      instance_type: Instance Segmentation
      train_dataset: COCO (train)
      train_epochs: 36
      mAP: 42.9
      AP50: 65.8
      AP75: 46.4
      mAPs: null
      mAPm: null
      mAPl: null
      gflops: 747.0
    semantic_seg_results:
    - head: UPerNet
      dataset: ADE20K (val)
      train_dataset: ADE20K (train)
      train_epochs: 128
      crop_size: 512
      ms_m_iou: null
      ms_pixel_accuracy: null
      ms_mean_accuracy: null
      ss_m_iou: 44.7
      ss_pixel_accuracy: null
      ss_mean_accuracy: null
      flip_test: false
      gflops: 946.0
- name: Iwin-S
  m_parameters: 51.6
  fps_measurements:
  - resolution: 224
    gpu: V100
    precision: FP32
    fps: 410
    batch_size: 256
  pretrained_backbones:
  - name: Iwin-S-IN1k
    pretrain_dataset: ImageNet-1k
    pretrain_method: Supervised
    pretrain_resolution: 224
    pretrain_epochs: 300
    classification_results:
    - dataset: ImageNet-1k
      resolution: 224
      top_1: 83.4
      top_5: null
      gflops: 9.0
    - dataset: ImageNet-1k
      resolution: 384
      fine_tune_dataset: ImageNet-1k
      fine_tune_epochs: 30
      fine_tune_resolution: 384
      top_1: 84.3
      top_5: null
      gflops: 27.7
    - dataset: ImageNet-1k
      resolution: 512
      fine_tune_dataset: ImageNet-1k
      fine_tune_epochs: 30
      fine_tune_resolution: 512
      top_1: 84.4
      top_5: null
      gflops: 52.0
    - dataset: ImageNet-1k
      resolution: 1024
      fine_tune_dataset: ImageNet-1k
      fine_tune_epochs: 30
      fine_tune_resolution: 1024
      top_1: 83.8
      top_5: null
      gflops: 207.9
    instance_results:
    - head: Mask R-CNN
      dataset: COCO (val)
      instance_type: Object Detection
      train_dataset: COCO (train)
      train_epochs: 12
      mAP: 43.7
      AP50: 67.0
      AP75: 47.4
      mAPs: null
      mAPm: null
      mAPl: null
      gflops: 358.0
    - head: Mask R-CNN
      dataset: COCO (val)
      instance_type: Instance Segmentation
      train_dataset: COCO (train)
      train_epochs: 12
      mAP: 40.0
      AP50: 63.9
      AP75: 42.5
      mAPs: null
      mAPm: null
      mAPl: null
      gflops: 358.0
    - head: Mask R-CNN
      dataset: COCO (val)
      instance_type: Object Detection
      train_dataset: COCO (train)
      train_epochs: 36
      mAP: 45.5
      AP50: 67.5
      AP75: 49.6
      mAPs: null
      mAPm: null
      mAPl: null
      gflops: 358.0
    - head: Mask R-CNN
      dataset: COCO (val)
      instance_type: Instance Segmentation
      train_dataset: COCO (train)
      train_epochs: 36
      mAP: 41.0
      AP50: 64.3
      AP75: 44.0
      mAPs: null
      mAPm: null
      mAPl: null
      gflops: 358.0
    - head: Cascade Mask R-CNN
      dataset: COCO (val)
      instance_type: Object Detection
      train_dataset: COCO (train)
      train_epochs: 36
      mAP: 49.4
      AP50: 68.1
      AP75: 53.3
      mAPs: null
      mAPm: null
      mAPl: null
      gflops: 837.0
    - head: Cascade Mask R-CNN
      dataset: COCO (val)
      instance_type: Instance Segmentation
      train_dataset: COCO (train)
      train_epochs: 36
      mAP: 43.0
      AP50: 65.6
      AP75: 46.4
      mAPs: null
      mAPm: null
      mAPl: null
      gflops: 837.0
    semantic_seg_results:
    - head: UPerNet
      dataset: ADE20K (val)
      train_dataset: ADE20K (train)
      train_epochs: 128
      crop_size: 512
      ms_m_iou: null
      ms_pixel_accuracy: null
      ms_mean_accuracy: null
      ss_m_iou: 47.5
      ss_pixel_accuracy: null
      ss_mean_accuracy: null
      flip_test: false
      gflops: 1038.0
- name: Iwin-B
  m_parameters: 91.2
  fps_measurements:
  - resolution: 224
    gpu: V100
    precision: FP32
    fps: 271
    batch_size: 256
  pretrained_backbones:
  - name: Iwin-B-IN1k
    pretrain_dataset: ImageNet-1k
    pretrain_method: Supervised
    pretrain_resolution: 224
    pretrain_epochs: 300
    classification_results:
    - dataset: ImageNet-1k
      resolution: 224
      top_1: 83.5
      top_5: null
      gflops: 15.9
    - dataset: ImageNet-1k
      resolution: 384
      fine_tune_dataset: ImageNet-1k
      fine_tune_epochs: 30
      fine_tune_resolution: 384
      top_1: 84.9
      top_5: null
      gflops: 48.3
    - dataset: ImageNet-1k
      resolution: 512
      fine_tune_dataset: ImageNet-1k
      fine_tune_epochs: 30
      fine_tune_resolution: 512
      top_1: 85.1
      top_5: null
      gflops: 89.5
    - dataset: ImageNet-1k
      resolution: 1024
      fine_tune_dataset: ImageNet-1k
      fine_tune_epochs: 30
      fine_tune_resolution: 1024
      top_1: 85.0
      top_5: null
      gflops: 358.2
    semantic_seg_results:
    - head: UPerNet
      dataset: ADE20K (val)
      train_dataset: ADE20K (train)
      train_epochs: 128
      crop_size: 512
      ms_m_iou: null
      ms_pixel_accuracy: null
      ms_mean_accuracy: null
      ss_m_iou: 48.9
      ss_pixel_accuracy: null
      ss_mean_accuracy: null
      flip_test: false
      gflops: 1189.0
  - name: Iwin-B-IN22k
    pretrain_dataset: ImageNet-22k
    pretrain_method: Supervised
    pretrain_resolution: 224
    pretrain_epochs: 90
    classification_results:
    - dataset: ImageNet-1k
      resolution: 224
      fine_tune_dataset: ImageNet-1k
      fine_tune_epochs: 30
      fine_tune_resolution: 224
      top_1: 85.5
      top_5: null
      gflops: 15.9
    - dataset: ImageNet-1k
      resolution: 384
      fine_tune_dataset: ImageNet-1k
      fine_tune_epochs: 30
      fine_tune_resolution: 384
      top_1: 86.6
      top_5: null
      gflops: 48.3
    - dataset: ImageNet-1k
      resolution: 512
      fine_tune_dataset: ImageNet-1k
      fine_tune_epochs: 30
      fine_tune_resolution: 512
      top_1: 86.1
      top_5: null
      gflops: 89.5
    - dataset: ImageNet-1k
      resolution: 1024
      fine_tune_dataset: ImageNet-1k
      fine_tune_epochs: 30
      fine_tune_resolution: 1024
      top_1: 85.6
      top_5: null
      gflops: 358.2
- name: Iwin-L
  m_parameters: 204.3
  fps_measurements:
  - resolution: 224
    gpu: V100
    precision: FP32
    fps: 138
    batch_size: 256
  pretrained_backbones:
  - name: Iwin-L-IN22k
    pretrain_dataset: ImageNet-22k
    pretrain_method: Supervised
    pretrain_resolution: 224
    pretrain_epochs: 90
    classification_results:
    - dataset: ImageNet-1k
      resolution: 224
      fine_tune_dataset: ImageNet-1k
      fine_tune_epochs: 30
      fine_tune_resolution: 224
      top_1: 86.4
      top_5: null
      gflops: 35.4
    - dataset: ImageNet-1k
      resolution: 384
      fine_tune_dataset: ImageNet-1k
      fine_tune_epochs: 30
      fine_tune_resolution: 384
      top_1: 87.4
      top_5: null
      gflops: 106.6
