name: NAT
model_type: Attention
hierarchical: true
pretrain_method: Supervised
pub_date: "2022-04-15"
paper: https://arxiv.org/abs/2204.07143
github: https://github.com/SHI-Labs/Neighborhood-Attention-Transformer
backbones:
  - name: NAT-M
    m_parameters: 20.0
    fps_measurements:
      - resolution: 224
        gpu: A100
        precision: AMP
        fps: 2135
        batch_size: 256
    pretrained_backbones:
      - name: NAT-M-IN1k
        pretrain_dataset: ImageNet-1k
        pretrain_method: Supervised
        pretrain_resolution: 224
        pretrain_epochs: 300
        classification_results:
          - dataset: ImageNet-1k
            resolution: 224
            top_1: 81.8
            top_5: null
            gflops: 2.7
        instance_results:
          - head: Mask R-CNN
            dataset: COCO (val)
            instance_type: Object Detection
            train_dataset: COCO (train)
            train_epochs: 36
            mAP: 46.5
            AP50: 68.1
            AP75: 51.3
            mAPs: null
            mAPm: null
            mAPl: null
            gflops: 225.0
            fps_measurements:
              - resolution: 1280
                gpu: A100
                precision: AMP
                fps: 54.1
                batch_size: null
          - head: Mask R-CNN
            dataset: COCO (val)
            instance_type: Instance Segmentation
            train_dataset: COCO (train)
            train_epochs: 36
            mAP: 41.7
            AP50: 65.2
            AP75: 44.7
            mAPs: null
            mAPm: null
            mAPl: null
            gflops: 225.0
            fps_measurements:
              - resolution: 1280
                gpu: A100
                precision: AMP
                fps: 54.1
                batch_size: null
          - head: Cascade Mask R-CNN
            dataset: COCO (val)
            instance_type: Object Detection
            train_dataset: COCO (train)
            train_epochs: 36
            mAP: 50.3
            AP50: 68.9
            AP75: 54.9
            mAPs: null
            mAPm: null
            mAPl: null
            gflops: 704.0
            fps_measurements:
              - resolution: 1280
                gpu: A100
                precision: AMP
                fps: 27.8
                batch_size: null
          - head: Cascade Mask R-CNN
            dataset: COCO (val)
            instance_type: Instance Segmentation
            train_dataset: COCO (train)
            train_epochs: 36
            mAP: 43.6
            AP50: 66.4
            AP75: 47.2
            mAPs: null
            mAPm: null
            mAPl: null
            gflops: 704.0
            fps_measurements:
              - resolution: 1280
                gpu: A100
                precision: AMP
                fps: 27.8
                batch_size: null
        semantic_seg_results:
          - head: UPerNet
            dataset: ADE20K (val)
            train_dataset: ADE20K (train)
            train_epochs: 128
            crop_size: 512
            ms_m_iou: 46.4
            ms_pixel_accuracy: null
            ms_mean_accuracy: null
            ss_m_iou: 45.1
            ss_pixel_accuracy: null
            ss_mean_accuracy: null
            flip_test: false
            gflops: 900.0
            fps_measurements:
              - resolution: 512
                gpu: A100
                precision: AMP
                fps: 24.5
                batch_size: null
  - name: NAT-T
    m_parameters: 28.0
    fps_measurements:
      - resolution: 224
        gpu: A100
        precision: AMP
        fps: 1541.0
        batch_size: 256
    pretrained_backbones:
      - name: NAT-T-IN1k
        pretrain_dataset: ImageNet-1k
        pretrain_method: Supervised
        pretrain_resolution: 224
        pretrain_epochs: 300
        classification_results:
          - dataset: ImageNet-1k
            resolution: 224
            top_1: 83.2
            top_5: null
            gflops: 4.3
        instance_results:
          - head: Mask R-CNN
            dataset: COCO (val)
            instance_type: Object Detection
            train_dataset: COCO (train)
            train_epochs: 36
            mAP: 47.7
            AP50: 69.0
            AP75: 52.6
            mAPs: null
            mAPm: null
            mAPl: null
            gflops: 258.0
            fps_measurements:
              - resolution: 1280
                gpu: A100
                precision: AMP
                fps: 44.5
                batch_size: null
          - head: Mask R-CNN
            dataset: COCO (val)
            instance_type: Instance Segmentation
            train_dataset: COCO (train)
            train_epochs: 36
            mAP: 42.6
            AP50: 66.1
            AP75: 45.9
            mAPs: null
            mAPm: null
            mAPl: null
            gflops: 258.0
            fps_measurements:
              - resolution: 1280
                gpu: A100
                precision: AMP
                fps: 44.5
                batch_size: null
          - head: Cascade Mask R-CNN
            dataset: COCO (val)
            instance_type: Object Detection
            train_dataset: COCO (train)
            train_epochs: 36
            mAP: 51.4
            AP50: 70.0
            AP75: 55.9
            mAPs: null
            mAPm: null
            mAPl: null
            gflops: 737.0
            fps_measurements:
              - resolution: 1280
                gpu: A100
                precision: AMP
                fps: 24.9
                batch_size: null
          - head: Cascade Mask R-CNN
            dataset: COCO (val)
            instance_type: Instance Segmentation
            train_dataset: COCO (train)
            train_epochs: 36
            mAP: 44.5
            AP50: 67.6
            AP75: 47.9
            mAPs: null
            mAPm: null
            mAPl: null
            gflops: 737.0
            fps_measurements:
              - resolution: 1280
                gpu: A100
                precision: AMP
                fps: 24.9
                batch_size: null
        semantic_seg_results:
          - head: UPerNet
            dataset: ADE20K (val)
            train_dataset: ADE20K (train)
            train_epochs: 128
            crop_size: 512
            ms_m_iou: 48.4
            ms_pixel_accuracy: null
            ms_mean_accuracy: null
            ss_m_iou: 47.1
            ss_pixel_accuracy: null
            ss_mean_accuracy: null
            flip_test: false
            gflops: 934.0
            fps_measurements:
              - resolution: 512
                gpu: A100
                precision: AMP
                fps: 21.4
                batch_size: null
  - name: NAT-S
    m_parameters: 51.0
    fps_measurements:
      - resolution: 224
        gpu: A100
        precision: AMP
        fps: 1051.0
        batch_size: 256
    pretrained_backbones:
      - name: NAT-S-IN1k
        pretrain_dataset: ImageNet-1k
        pretrain_method: Supervised
        pretrain_resolution: 224
        pretrain_epochs: 300
        classification_results:
          - dataset: ImageNet-1k
            resolution: 224
            top_1: 83.7
            top_5: null
            gflops: 7.8
        instance_results:
          - head: Mask R-CNN
            dataset: COCO (val)
            instance_type: Object Detection
            train_dataset: COCO (train)
            train_epochs: 36
            mAP: 48.4
            AP50: 69.8
            AP75: 53.2
            mAPs: null
            mAPm: null
            mAPl: null
            gflops: 330.0
            fps_measurements:
              - resolution: 1280
                gpu: A100
                precision: AMP
                fps: 34.8
                batch_size: null
          - head: Mask R-CNN
            dataset: COCO (val)
            instance_type: Instance Segmentation
            train_dataset: COCO (train)
            train_epochs: 36
            mAP: 43.2
            AP50: 66.9
            AP75: 46.5
            mAPs: null
            mAPm: null
            mAPl: null
            gflops: 330.0
            fps_measurements:
              - resolution: 1280
                gpu: A100
                precision: AMP
                fps: 34.8
                batch_size: null
          - head: Cascade Mask R-CNN
            dataset: COCO (val)
            instance_type: Object Detection
            train_dataset: COCO (train)
            train_epochs: 36
            mAP: 52.0
            AP50: 70.4
            AP75: 56.3
            mAPs: null
            mAPm: null
            mAPl: null
            gflops: 809.0
            fps_measurements:
              - resolution: 1280
                gpu: A100
                precision: AMP
                fps: 21.7
                batch_size: null
          - head: Cascade Mask R-CNN
            dataset: COCO (val)
            instance_type: Instance Segmentation
            train_dataset: COCO (train)
            train_epochs: 36
            mAP: 44.9
            AP50: 68.1
            AP75: 48.6
            mAPs: null
            mAPm: null
            mAPl: null
            gflops: 809.0
            fps_measurements:
              - resolution: 1280
                gpu: A100
                precision: AMP
                fps: 21.7
                batch_size: null
        semantic_seg_results:
          - head: UPerNet
            dataset: ADE20K (val)
            train_dataset: ADE20K (train)
            train_epochs: 128
            crop_size: 512
            ms_m_iou: 49.5
            ms_pixel_accuracy: null
            ms_mean_accuracy: null
            ss_m_iou: 48.0
            ss_pixel_accuracy: null
            ss_mean_accuracy: null
            flip_test: false
            gflops: 1010.0
            fps_measurements:
              - resolution: 512
                gpu: A100
                precision: AMP
                fps: 17.9
                batch_size: null
  - name: NAT-B
    m_parameters: 90.0
    fps_measurements:
      - resolution: 224
        gpu: A100
        precision: AMP
        fps: 783.0
        batch_size: 256
    pretrained_backbones:
      - name: NAT-B-IN1k
        pretrain_dataset: ImageNet-1k
        pretrain_method: Supervised
        pretrain_resolution: 224
        pretrain_epochs: 300
        classification_results:
          - dataset: ImageNet-1k
            resolution: 224
            top_1: 84.3
            top_5: null
            gflops: 13.7
        instance_results:
          - head: Cascade Mask R-CNN
            dataset: COCO (val)
            instance_type: Object Detection
            train_dataset: COCO (train)
            train_epochs: 36
            mAP: 52.5
            AP50: 71.1
            AP75: 57.1
            mAPs: null
            mAPm: null
            mAPl: null
            gflops: 931.0
            fps_measurements:
              - resolution: 1280
                gpu: A100
                precision: AMP
                fps: 18.6
                batch_size: null
          - head: Cascade Mask R-CNN
            dataset: COCO (val)
            instance_type: Instance Segmentation
            train_dataset: COCO (train)
            train_epochs: 36
            mAP: 45.2
            AP50: 68.6
            AP75: 49.0
            mAPs: null
            mAPm: null
            mAPl: null
            gflops: 931.0
            fps_measurements:
              - resolution: 1280
                gpu: A100
                precision: AMP
                fps: 18.6
                batch_size: null
        semantic_seg_results:
          - head: UPerNet
            dataset: ADE20K (val)
            train_dataset: ADE20K (train)
            train_epochs: 128
            crop_size: 512
            ms_m_iou: 49.7
            ms_pixel_accuracy: null
            ms_mean_accuracy: null
            ss_m_iou: 48.5
            ss_pixel_accuracy: null
            ss_mean_accuracy: null
            flip_test: false
            gflops: 1137.0
            fps_measurements:
              - resolution: 512
                gpu: A100
                precision: AMP
                fps: 15.6
                batch_size: null
